# Utilisez une image de base PostgreSQL
FROM postgres:latest

# Définissez l'utilisateur et le mot de passe par défaut pour la base de données
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Définissez le nom de la base de données par défaut
ENV POSTGRES_DB=mydb
